name: Cleanup Only

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm install

      - name: Cleanup old episodes
        env:
          CLEANUP_SECRET_KEY: ${{ secrets.CLEANUP_SECRET_KEY }}
        run: node api/cleanup-old-episodes.js 