name: Cleanup Only

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm install

      - name: Cleanup old episodes
        env:
          CLEANUP_SECRET_KEY: ${{ secrets.CLEANUP_SECRET_KEY }}
        run: node api/cleanup-old-episodes.js 

      - name: Commit and push deletions
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -u public/
          git commit -m "chore: delete old podcast episodes [skip ci]" || echo "No changes to commit"
          git push 